### ISSUE TITLE
Error when running generator

### ISSUE THREAD

**Issue by JohnMerrick** [ederribeiro/generator-apu-codeigniter#2]
Hi,

I get the following error when i run the generator with: yo apu-codeigniter

events.js:141
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected token ILLEGAL in /usr/local/lib/node_modules/generator-apu-codeigniter/app/templates/_Gruntfile.js while compiling ejs
    at Function (native)
    at Object.Template.compile (/usr/local/lib/node_modules/generator-apu-codeigniter/node_modules/ejs/lib/ejs.js:464:12)
    at Object.compile (/usr/local/lib/node_modules/generator-apu-codeigniter/node_modules/ejs/lib/ejs.js:288:16)
    at handleCache (/usr/local/lib/node_modules/generator-apu-codeigniter/node_modules/ejs/lib/ejs.js:147:16)
    at Object.exports.render (/usr/local/lib/node_modules/generator-apu-codeigniter/node_modules/ejs/lib/ejs.js:315:10)
    at copy.process (/usr/local/lib/node_modules/generator-apu-codeigniter/node_modules/mem-fs-editor/actions/copy-tpl.js:18:18)
    at applyProcessingFunc (/usr/local/lib/node_modules/generator-apu-codeigniter/node_modules/mem-fs-editor/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-apu-codeigniter/node_modules/mem-fs-editor/actions/copy.js:56:24)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-apu-codeigniter/node_modules/mem-fs-editor/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl](/usr/local/lib/node_modules/generator-apu-codeigniter/node_modules/mem-fs-editor/actions/copy-tpl.js:16:8)

**Comment by ederribeiro** [comment]
fixed!

Thanks.
